version: '3.0'

services:
  fiddle:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/fiddle.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "83:80"
    depends_on:
      - fiddle
      - pocketbase
  pocketbase:
    build:
      context: .docker/pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - pocketbase:/pb/pb_data

volumes:
  pocketbase: